#!/bin/bash

make
sudo mv camctrl /usr/local/bin/camctrl
sudo mkdir -p /usr/local/share/camctrl/docs
sudo mkdir -p /usr/share/camctrl/Projects/example
sudo cp res/docs/* /usr/local/share/camctrl/docs/
sudo cp cfg/init /usr/local/share/camctrl/init
sudo cp cfg/.bashrc /home/pi/.bashrc
sudo cp cfg/autologin.conf /etc/systemd/system/getty@tty1.service.d/autologin.conf
